### PR TITLE
[PRG] document new BASIC commands, HW cleanup

### PR DESCRIPTION
**Pull request by mooinglemur**
After adding the docs for BASIC commands from https://github.com/X16Community/x16-rom/pull/40 and for the enhancement https://github.com/X16Community/x16-rom/pull/37 I also made some changes to the hardware chapter.

### CODE REVIEW

**Review by tomxp411 — COMMENTED** [review]
Are you sure on the frame rates? NTSC is 29.97 Hz per frame and 59.94 per field. I’d expect VGA to be an even 60, although I’m betting a VGA monitor can handle 59.94.

**Review by tomxp411 — COMMENTED** [review]
Also, if this is a 24 pin ATX jack, then the -12v is 14, not 12.

**Comment by mooinglemur** [comment]
> Also, if this is a 24 pin ATX jack, then the -12v is 14, not 12.

Clarified with an update.

**Comment by mooinglemur** [comment]
> Are you sure on the frame rates? NTSC is 29.97 Hz per frame and 59.94 per field. I’d expect VGA to be an even 60, although I’m betting a VGA monitor can handle 59.94.

    parameter H_SYNC            = 118;
    parameter H_BACK_PORCH      = 152;
    parameter H_ACTIVE          = 1280;
    parameter H_FRONT_PORCH     = 38;
    parameter H_TOTAL           = H_SYNC + H_BACK_PORCH + H_ACTIVE + H_FRONT_PORCH;

    parameter H_HALF                   = H_TOTAL / 2;

H_TOTAL = 1588, H_HALF = 794
H_HALF multiplied by 525 scan lines for both VGA and composite modes = 416850
25MHz clock on the VERA divided by above = 59.973611611 Hz

VGA = 800 x 525 including both blanking areas divided into the 25MHz clock = 59.523809524 Hz

**Comment by mooinglemur** [comment]
Both VGA and composite are slightly out of spec, but not excessively so.  It wasn't out of the ordinary for gaming consoles to have composite sync be something slightly out of spec.  The NES, for example output at ~60.098814 240p frames per second.

**Comment by tomxp411** [comment]
> > Are you sure on the frame rates? NTSC is 29.97 Hz per frame and 59.94 per field. I’d expect VGA to be an even 60, although I’m betting a VGA monitor can handle 59.94.
> 
> ```
> parameter H_SYNC            = 118;
> parameter H_BACK_PORCH      = 152;
> parameter H_ACTIVE          = 1280;
> parameter H_FRONT_PORCH     = 38;
> parameter H_TOTAL           = H_SYNC + H_BACK_PORCH + H_ACTIVE + H_FRONT_PORCH;
> 
> parameter H_HALF                   = H_TOTAL / 2;
> ```
> 
> H_TOTAL = 1588, H_HALF = 794 H_HALF multiplied by 525 scan lines which applies to both VGA and composite modes = 416850 25MHz clock on the VERA divided by above = 59.973611611 Hz composite
> 
> VGA = 800 x 525 including both blanking areas divided into the 25MHz clock = 59.523809524 Hz VGA

Thanks. I just wanted to confirm that, since that would make it slightly out of spec for NTSC, but probably close  enough.  That’s another thing I can check with a scope, later.

**Review by indigodarkwolf — APPROVED** [review]
👍

**Pull request merged**
