### PR TITLE
Clarify cartridge MMIO usage

### PR DESCRIPTION
**Pull request by m00dawg**
Update based on below plus some Discord convos. 

TLDR:

Documentation change to suggest cartridges which require MMIO use IO7 first and expansion cards start with IO5 first (5-7 as those are the 2MHz ranges since there are only 2 8MHz ranges).

### CODE REVIEW

**Comment by jburks** [comment]
IO ranges cannot physically be broken up into pieces smaller than 32 bytes with the current architecture. A cartridge MMIO range would have to consume a full 32 byte range on a 32 byte boundary.

**Comment by m00dawg** [comment]
> IO ranges cannot physically be broken up into pieces smaller than 32 bytes with the current architecture. A cartridge MMIO range would have to consume a full 32 byte range on a 32 byte boundary.

Thanks for the clarity there! That's unfortunate but is what it is. I updated the PR back to a sort of "Plan A" but a lighter version. Instead of preventing internal expansion cards from using IO7, the docs simply suggest using IO7 last in the system and carts that use MMIO should use IO7 first.

**Comment by jkominek** [comment]
As somebody [designing hardware](https://github.com/jkominek/x16-i2c) I'd be happy to see more guidelines like this in the docs. That said, I'd like to see these sorts of guidelines expanded to cover the banked ROM/RAM range.

Even just "cartridges start at the bottom of the ROM bank range, expansion cards at the top end, expansion cards should go to **great lengths** to avoid using more than 8 banks" would be _wonderful_.

**Comment by m00dawg** [comment]
Indeed I too am hardware minded here with plans for a cartridge that may end up using MMIO (though I may also be able to get by with I2C for my specific application). I'm in favor of more standards and information vs less. It doesn't mean folks can't ignore the standards and do as they please. That was, oddly, a big concern when discussing this on Discord, with some vocal folks intentionally wanting no standard rather than a standard they can violate. The same calamity ensues regardless but for those of us that can and are willing to abide by guidelines, it's ultimately better for other folks making hardware and especially the user. In case where folks need to violate the guidelines, then at least there is good info for what stuff might not be compatible and how.

Knowledge Is Power, in other words.

**Review by mooinglemur — APPROVED** [review]

**Pull request merged**
