### PR TITLE
Add complete update guide

### PR DESCRIPTION
**Pull request by stople**
This will be rewritten to markdown. Just pushing what I have now in the meantime.

### CODE REVIEW

**Comment by stople** [comment]
This guide is ready for review. @stefan-b-jakobsson @mooinglemur

**Comment by stople** [comment]
One main motivation for this guide is to collect all the relevant info in one place, and, document what to do in which order.

**Comment by stople** [comment]
One thing I forgot to write, was to ensure that the user do not accidentally put VERA or SMC stuff in the same folder as ROM when using x16-flash, to ensure stuff gets programmed in the correct order

**Comment by stefan-b-jakobsson** [comment]
Great work compiling all that information. Looks solid to me.

The only thing I was thinking about was if we should refer users to an unreleased SMC version.

**Comment by stople** [comment]
So, users have 3 options when programming SMC FW:
- SMCUPDATE-47.2.3.PRG (bundled update tool)
- SMCUPDATE-2.0 (tool where you specify .hex file. Note that this tool does NOT support the v3 bootloader)
- x16-flash (this tool always works, but, gives bad recommendation together with bad v2 bootloader)

Given these options, I think the bundled installer seem like the best choice. As you then also can use it to install the boot-v3-failsafe.

If you agree to suggest to use this tool as the preferred option off course. If you consider this SMC update tool (or its bundled firmware version) as unreleased, perhaps better to release something first, and then, refer to that? As this option seem like a very user friendly way of installing new firmware, and, it have much better compatibility with the new bootloader.

**Review by mooinglemur — APPROVED** [review]

**Pull request merged**
