### PR TITLE
Update X16 Reference - 07 - Memory Map.md

### PR DESCRIPTION
**Pull request by Yazwh0**
Remove mention of VIA2.

### CODE REVIEW

**Comment by mooinglemur** [comment]
VIA2 still exists in that range if it is installed.  x16emu can enable it with `-via2`, and Proto 4 dev boards still have a real VIA2.  I think we should leave it documented.

**Comment by tomxp411** [comment]
VIA2 still exists. It's on the dev boards, and it has its own header on the motherboard. 

It may be removed from Gen-2, but we are not there, yet, and it belongs in the documentation.

**Comment by Yazwh0** [comment]
If you want to keep it, but its going to be removed, then that should be documented.

**Comment by mooinglemur** [comment]
Just because it's going to be an option doesn't mean the I/O range no longer exists.  It exists on the dev boards, and there are likely to be at least a hundred of those.  According to David, it will exist as an optional component on later boards through the expansion bus. It's probably best have documented what exists today rather than what is forecast to exist or not exist. It's not out of the realm of possibility that they decide to change their mind and leave it in after all.  If ever boards exist that don't have the chip, perhaps then we make a note that the chip is an option on some boards.  For now it exists on all boards.

**Comment by Yazwh0** [comment]
> Just because it's going to be an option doesn't mean the I/O range no longer exists. It exists on the dev boards, and there are likely to be at least a hundred of those. According to David, it will exist as an optional component on later boards through the expansion bus. It's probably best have documented what exists today rather than what is forecast to exist or not exist. It's not out of the realm of possibility that they decide to change their mind and leave it in after all. If ever boards exist that don't have the chip, perhaps then we make a note that the chip is an option on some boards. For now it exists on all boards.

Thats a great explanation. Exactly what should be in the doc explaining what could happen to the VIA2 and indeed this IO area.

**Pull request closed without merging**
